# Generated by Django 4.1 on 2022-08-12 15:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('image', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('technique', models.CharField(max_length=200, verbose_name='Техника')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('year', models.IntegerField()),
                ('size_width', models.IntegerField(verbose_name='Высота')),
                ('size_height', models.IntegerField(verbose_name='Ширина')),
                ('image', models.ImageField(upload_to='')),
                ('on_sale', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='shop.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.CharField(choices=[('New', 'NEW'), ('Acc', 'ACCEPTED'), ('Paid', 'PAID'), ('Cl', 'CLOSED'), ('Canc', 'CANCELLED')], default='New', max_length=10)),
                ('commentary', models.TextField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.customer')),
                ('items', models.ManyToManyField(to='shop.artwork')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('items', models.ManyToManyField(to='shop.artwork')),
            ],
        ),
    ]
